### ISSUE TITLE
Prune outputs of pipeline

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/codex-pipeline#12]
We don't necessarily need to expose the raw outputs of Cytokit as a "final" output of the pipeline -- just our conversion of those files to OME-TIFF. Remove the Cytokit `processor` and `operator` output, plus or minus some other files.

**Comment by mkeays** [comment]
I can do this today, I think we just need the `for_viz_dir` directory and the two containing the files linked therein, `sprm_output_dir` and `ome_tiff_output`.

**Comment by mkeays** [comment]
Think I will also keep the `experiment_config`. Doesn't have to be part of the files for the UI but may be of interest to some users.
